server:
  port: 8006
spring:
  application:
    name: zth-order-srv
  banner:
    location: classpath:banner.txt
  zipkin:
    baseUrl: http://localhost:9411
  cassandra:
    port: 9042
    username: cassandra_user
    password: cassandra_password
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
    keyspace-name: order_ksp
      
